const ingredients: {label: string}[] = [
  { label: 'Salt' },
  { label: 'Pepper' },
  { label: 'Garlic' },
  { label: 'Onion' },
  { label: 'Olive Oil' },
  { label: 'Butter' },
  { label: 'Basil' },
  { label: 'Thyme' },
  { label: 'Rosemary' },
  { label: 'Parsley' },
  { label: 'Cilantro' },
  { label: 'Ginger' },
  { label: 'Cumin' },
  { label: 'Coriander' },
  { label: 'Turmeric' },
  { label: 'Cinnamon' },
  { label: 'Nutmeg' },
  { label: 'Paprika' },
  { label: 'Chili Powder' },
  { label: 'Cayenne Pepper' },
  { label: 'Curry Powder' },
  { label: 'Mustard' },
  { label: 'Ketchup' },
  { label: 'Mayonnaise' },
  { label: 'Vinegar' },
  { label: 'Lemon Juice' },
  { label: 'Soy Sauce' },
  { label: 'Fish Sauce' },
  { label: 'Worcestershire Sauce' },
  { label: 'Honey' },
  { label: 'Sugar' },
  { label: 'Flour' },
  { label: 'Cornstarch' },
  { label: 'Baking Powder' },
  { label: 'Baking Soda' },
  { label: 'Yeast' },
  { label: 'Milk' },
  { label: 'Cream' },
  { label: 'Eggs' },
  { label: 'Cheese' },
  { label: 'Yogurt' },
  { label: 'Sour Cream' },
  { label: 'Chicken' },
  { label: 'Beef' },
  { label: 'Pork' },
  { label: 'Lamb' },
  { label: 'Fish' },
  { label: 'Shrimp' },
  { label: 'Scallops' },
  { label: 'Crab' },
  { label: 'Lobster' },
  { label: 'Rice' },
  { label: 'Pasta' },
  { label: 'Bread' },
  { label: 'Potatoes' },
  { label: 'Tomatoes' },
  { label: 'Cucumbers' },
  { label: 'Carrots' },
  { label: 'Broccoli' },
  { label: 'Spinach' },
  { label: 'Lettuce' },
  { label: 'Mushrooms' },
  { label: 'Zucchini' },
  { label: 'Eggplant' },
  { label: 'Avocado' },
  { label: 'Bananas' },
  { label: 'Strawberries' },
  { label: 'Blueberries' },
  { label: 'Apples' },
  { label: 'Oranges' },
  { label: 'Limes' },
  { label: 'Lemons' },
  { label: 'Grapes' },
  { label: 'Watermelon' },
  { label: 'Pineapple' },
  { label: 'Coconut' },
  { label: 'Mango' },
  { label: 'Peaches' },
  { label: 'Plums' },
  { label: 'Raspberries' },
  { label: 'Blackberries' },
  { label: 'Cherries' },
  { label: 'Hazelnuts' },
  { label: 'Almonds' },
  { label: 'Walnuts' },
  { label: 'Peanuts' },
  { label: 'Cashews' },
  { label: 'Pistachios' },
  { label: 'Sesame Seeds' },
  { label: 'Sunflower Seeds' },
  { label: 'Pumpkin Seeds' },
  { label: 'Flaxseeds' },
  { label: 'Quinoa' },
  { label: 'Couscous' },
  { label: 'Barley' },
  { label: 'Oats' },
  { label: 'Millet' },
  { label: 'Honeydew Melon' },
  { label: 'Cantaloupe' },
  { label: 'Kiwi' },
  { label: 'Fig' },
  { label: 'Dates' },
  { label: 'Powdered Sugar' },
  { label: 'Ham' },
  { label: 'Bell Pepper' },
  { label: 'Chocolate' },
  { label: 'Dark Chocolate' },
  { label: 'White Chocolate' },
  { label: 'Chia Seeds' },
  { label: 'Pumpkin' },
  { label: 'Cream Cheese' },
  { label: 'Brown Sugar' },
  { label: 'Bread Crumbs' },
  { label: 'Cooking Oil' },
  { label: 'Vegetable Oil' },
  { label: 'Kale' },
  { label: 'Red Pepper' },
  { label: 'Lentils' },
  { label: 'Sausage' },
  { label: 'Vanilla Extract' },
  { label: 'Maple Syrup' },
  { label: 'Coconut Milk' },
  { label: 'Peanut Butter' },
  { label: 'Tofu' },
  { label: 'Chickpeas' },
  { label: 'Sesame Oil' },
  { label: 'Red Wine Vinegar' },
  { label: 'Pomegranate' },
  { label: 'Asparagus' },
  { label: 'Cabbage' },
  { label: 'Hazelnut Butter' },
  { label: 'Almond Butter' },
  { label: 'Cashew Butter' },
  { label: 'Pistachio Butter' },
  { label: 'Peanut Sauce' },
  { label: 'Coconut Flour' },
  { label: 'Flaxseed Meal' },
  { label: 'Seaweed' },
  { label: 'Miso Paste' },
  { label: 'Tamari' },
  { label: 'Ramen Noodles' },
  { label: 'Soba Noodles' },
  { label: 'Udon Noodles' },
  { label: 'Buckwheat Noodles' },
  { label: 'Miso' },
  { label: 'Sake' },
  { label: 'Mirin' },
  { label: 'Wasabi' },
  { label: 'Nori' },
  { label: 'Tempeh' },
  { label: 'Seitan' },
  { label: 'Kimchi' },
  { label: 'Sriracha' },
  { label: 'Hoisin Sauce' },
  { label: 'Pesto' },
  { label: 'Artichokes' },
  { label: 'Capers' },
  { label: 'Olives' },
  { label: 'Anchovies' },
  { label: 'Saffron' },
  { label: 'Garam Masala' },
  { label: 'Cardamom' },
  { label: 'Allspice' },
  { label: 'Star Anise' },
  { label: 'Chives' },
  { label: 'Green Onion' },
  { label: 'Artichoke Hearts' },
];

export default ingredients;
